[build]
  # Comando de instalación. Netlify lo ejecuta automáticamente.
  command = "npm install" 

[functions]
  # Le dice a Netlify que busque funciones en la carpeta 'functions'
  directory = "functions"